apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-service-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: tutorialservice-kube
        image: lexschilperoord/tutorialservice:latest
      - name: database-kube
        image: lexschilperoord/tutorialservice:db
        env:
        - name: SQLSERVER_CONNECTIONSTRING
          value: "Server=database-kube;Database=TutorialService.Data;User=sa;Password=yourStrong(!)Password;"
---
apiVersion: v1
kind: Service
metadata:
  name: tutorial-service-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001