version: '3.4'

services:
  tutorialservice:
    image: ${DOCKER_REGISTRY-}tutorialservice
    build:
      context: .
      dockerfile: TutorialService/Dockerfile
    depends_on:
      - db

  db:
    image: ${DOCKER_REGISTRY-}mcr.microsoft.com/mssql/server:2022-latest
    container_name: TutorialServiceDB
    environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"
    ports:
      - "1414:1414"