apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: tutorialservice
  name: tutorialservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tutorialservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: tutorialservice
    spec:
      containers:
        - image: lexschilperoord/tutorialservice:latest
          name: tutorialservicedockercompose
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
